version: "3.2"
services:
  db:
    image: postgres:14
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=artigo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    image: dacit/api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    working_dir: /api/dacit_api/
    volumes:
      - type: bind
        source: ./api
        target: /api
    environment:
      - POETRY_VIRTUALENVS_CREATE=False
      - PYTHONPATH=/api/dacit_api/
    depends_on:
      - db
    ports:
      - 5002:8000
# Activate again when shipping container
#    env_file:
#      - ./api/src/artigo_api/.env
    
  web:
    image: dacit/dacit
    build:
      context: .
      dockerfile: ./dacit/Dockerfile
    volumes:
      - type: bind
        source: ./dacit/build/web
        target: /web
    working_dir: /dacit
    depends_on:
      - api
    ports:
      - 5001:80
