# Generated by Django 4.1.7 on 2023-04-09 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DacitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255)),
                ('public_id', models.BigIntegerField(unique=True)),
                ('active_language', models.CharField(choices=[('DE', 'German'), ('EN', 'English')], default='DE', max_length=2)),
                ('active_dialect', models.CharField(choices=[('ST', 'Standard'), ('BY', 'Bavarian')], default='ST', max_length=2)),
                ('manufacturer', models.CharField(choices=[('CL', 'Cochlear Limited'), ('AB', 'Advancedbionics'), ('ME', 'MED-EL'), ('NC', 'Neurelec'), ('NN', 'Nurotron')], default=None, max_length=2, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('D', 'Divers')], default=None, max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio')),
                ('language', models.CharField(choices=[('DE', 'German'), ('EN', 'English')], default='DE', max_length=2)),
                ('dialect', models.CharField(choices=[('ST', 'Standard'), ('BY', 'Bavarian')], default='ST', max_length=2)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text_Stimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('user_audio_creatable', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('DE', 'German'), ('EN', 'English')], default='DE', max_length=2)),
                ('wd_lexeme_url', models.CharField(max_length=50)),
                ('wd_item_url', models.CharField(max_length=50)),
                ('wc_picture_url', models.CharField(max_length=1500)),
                ('description', models.CharField(max_length=1000)),
                ('creator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_description', models.CharField(max_length=500)),
                ('relationship', models.CharField(choices=[('P', 'Parent'), ('S', 'Sibling'), ('F', 'Friend'), ('G', 'Grandparent'), ('T', 'Therapist')], default='F', max_length=1)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Min_Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_pair_class', models.CharField(choices=[('B_W', 'B W'), ('F_W', 'F W'), ('H_R', 'H R'), ('K_T', 'K T'), ('PF_T', 'Pf F'), ('R_L', 'R L')], default=None, max_length=4)),
                ('first_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_part', to='dacit_app.text_stimulus')),
                ('second_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_part', to='dacit_app.text_stimulus')),
            ],
        ),
        migrations.CreateModel(
            name='Audio_to_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_sent', models.DateTimeField(auto_now_add=True)),
                ('ts_recieved', models.DateTimeField()),
                ('skipped', models.BooleanField()),
                ('mode', models.CharField(max_length=100)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacit_app.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='text_stimulus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacit_app.text_stimulus'),
        ),
        migrations.CreateModel(
            name='Text_Stimulus_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text_stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacit_app.text_stimulus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'text_stimulus')},
            },
        ),
    ]
