# Generated by Django 4.1.5 on 2023-01-11 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=5000, null=True)),
                ('last_name', models.CharField(max_length=5000, null=True)),
                ('email', models.EmailField(max_length=5000, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('relationship', models.CharField(choices=[('P', 'Parent'), ('S', 'Sibling'), ('F', 'Friend'), ('G', 'Grandparent'), ('T', 'Therapist')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio')),
                ('language', models.CharField(max_length=2)),
                ('dicalect', models.CharField(max_length=100)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CI_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('CL', 'Cochlear Limited'), ('AB', 'Advanced Bionics'), ('ME', 'MED-EL'), ('NC', 'Neurelec'), ('NN', 'Nurotron')], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('theraphist', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text_Stimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('user_audio_creatable', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('DE', 'German'), ('EN', 'English')], default='DE', max_length=2)),
                ('wd_lexeme_url', models.CharField(max_length=50)),
                ('wd_item_url', models.CharField(max_length=50)),
                ('wc_picture_url', models.CharField(max_length=1500)),
                ('description', models.CharField(max_length=1000)),
                ('creator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Min_Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_pair_class', models.CharField(choices=[('B_W', 'B W'), ('F_W', 'F W'), ('H_R', 'H R'), ('K_T', 'K T'), ('PF_T', 'Pf F'), ('R_L', 'R L')], default=None, max_length=4)),
                ('first_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_part', to='dacit_app.text_stimulus')),
                ('second_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_part', to='dacit_app.text_stimulus')),
            ],
        ),
        migrations.CreateModel(
            name='CI_User_Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('dicalect', models.CharField(max_length=100)),
                ('ci_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacit_app.ci_user')),
            ],
        ),
        migrations.CreateModel(
            name='Audio_to_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_sent', models.DateTimeField(auto_now_add=True)),
                ('ts_recieved', models.DateTimeField()),
                ('skipped', models.BooleanField()),
                ('mode', models.CharField(max_length=100)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacit_app.audio')),
                ('ci_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacit_app.ci_user')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='text_stimulus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacit_app.text_stimulus'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ci_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dacit_app.ci_user'),
        ),
    ]
