# Generated by Django 4.1.7 on 2023-02-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dacituser',
            name='username',
            field=models.CharField(default=1245151512342, max_length=255),
            preserve_default=False,
        ),
    ]
