# Generated by Django 4.1.5 on 2023-02-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dacituser',
            name='public_id',
            field=models.CharField(default=4288579382461, max_length=500, unique=True),
        ),
    ]
