# Generated by Django 4.1 on 2022-09-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_stimulus',
            name='wc_picture_url',
            field=models.CharField(max_length=500),
        ),
    ]
