# Generated by Django 4.1.7 on 2023-02-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0002_dacituser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dacituser',
            name='public_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
