# Generated by Django 4.1 on 2022-09-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0002_alter_text_stimulus_wc_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_stimulus',
            name='wc_picture_url',
            field=models.CharField(max_length=1500),
        ),
    ]
