# Generated by Django 4.1.7 on 2023-05-31 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0003_alter_dacituser_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker_Dis_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.IntegerField(default=0)),
                ('timestamp_sent', models.DateTimeField(auto_now_add=True)),
                ('timestamp_recieved', models.DateTimeField()),
                ('speaker1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker1', to=settings.AUTH_USER_MODEL)),
                ('speaker2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'speaker1', 'speaker2')},
            },
        ),
        migrations.CreateModel(
            name='Min_Pair_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_equal', models.BooleanField()),
                ('answer_equal', models.BooleanField()),
                ('sent', models.IntegerField(default=0)),
                ('timestamp_sent', models.DateTimeField(auto_now_add=True)),
                ('timestamp_recieved', models.DateTimeField()),
                ('min_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacit_app.min_pair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'min_pair')},
            },
        ),
    ]
