# Generated by Django 4.1.2 on 2022-10-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0003_alter_text_stimulus_wc_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='text_stimulus',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dacit_app.text_stimulus'),
            preserve_default=False,
        ),
    ]
