# Generated by Django 4.1.7 on 2023-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0003_alter_dacituser_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dacituser',
            name='active_dicalect',
            field=models.CharField(choices=[('ST', 'Standard'), ('BY', 'Bavarian')], default='ST', max_length=2),
        ),
        migrations.AddField(
            model_name='dacituser',
            name='active_language',
            field=models.CharField(choices=[('DE', 'German'), ('EN', 'English')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='audio',
            name='dicalect',
            field=models.CharField(choices=[('ST', 'Standard'), ('BY', 'Bavarian')], default='ST', max_length=2),
        ),
        migrations.AlterField(
            model_name='audio',
            name='language',
            field=models.CharField(choices=[('DE', 'German'), ('EN', 'English')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='ci_user',
            name='manufacturer',
            field=models.CharField(choices=[('CL', 'Cochlear Limited'), ('AB', 'Advancedbionics'), ('ME', 'MED-EL'), ('NC', 'Neurelec'), ('NN', 'Nurotron')], max_length=2),
        ),
        migrations.AlterField(
            model_name='dacituser',
            name='relationship',
            field=models.CharField(choices=[('P', 'Parent'), ('S', 'Sibling'), ('F', 'Friend'), ('G', 'Grandparent'), ('T', 'Therapist')], default='F', max_length=1),
        ),
        migrations.DeleteModel(
            name='CI_User_Language',
        ),
    ]
