# Generated by Django 4.1.7 on 2023-03-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0004_dacituser_active_dicalect_dacituser_active_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='dicalect',
            new_name='dialect',
        ),
        migrations.RenameField(
            model_name='dacituser',
            old_name='active_dicalect',
            new_name='active_dialect',
        ),
    ]
