# Generated by Django 4.1.2 on 2022-10-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0004_audio_text_stimulus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='ci_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dacit_app.ci_user'),
        ),
    ]
