# Generated by Django 4.1.7 on 2023-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0004_speaker_dis_sent_min_pair_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='min_pair_sent',
            name='answer_equal',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='min_pair_sent',
            name='timestamp_recieved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='speaker_dis_sent',
            name='timestamp_recieved',
            field=models.DateTimeField(null=True),
        ),
    ]
