# Generated by Django 4.1.7 on 2023-03-29 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dacit_app', '0005_rename_dicalect_audio_dialect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_Stimulus_Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text_stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacit_app.text_stimulus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'text_stimulus')},
            },
        ),
    ]
